samples:
  subs_forward: raw_data/subs.bam
metaDMG-lca: ./metaDMG-cpp
names: raw_data/names.dmp.gz
nodes: raw_data/nodes.dmp.gz
acc2tax: raw_data/combined_taxid_accssionNO_20200726.gz
simscorelow: 0.95
simscorehigh: 1.0
editdistmin: 0
editdistmax: 10
minmapq: 0
lca_rank: ''
max_position: 15
weighttype: 1
fix_ncbi: 1
forward_only: true
forced: false
dir: data
cores: 1
cores_pr_fit: 1
bayesian: false
config_path: config.yaml
