samples:
  ESW_CMHR_Mex_9_S50_L005_R1_001_weigth0: raw_data/ESW_CMHR_Mex_9_S50_L005_R1_001.fq.sort.bam
  subs_weigth0: raw_data/subs.bam
  SPL_015_1444_weigth0: raw_data/SPL_015_1444.tmp.bam.merged.sort.bam
  gumpaper_weigth0: raw_data/gumpaper.sort.bam
  ESW_D44A_Library_blank2_weigth0: raw_data/ESW_D44A_Library_blank2.file.sort.bam
  SPL_195_9299_weigth0: raw_data/SPL_195_9299.tmp.bam.merged.sort.bam
metaDMG-lca: ./metaDMG-cpp
names: raw_data/names.dmp.gz
nodes: raw_data/nodes.dmp.gz
acc2tax: raw_data/combined_taxid_accssionNO_20200425.gz
simscorelow: 0.95
simscorehigh: 1.0
editdistmin: 0
editdistmax: 10
minmapq: 0
lca_rank: ''
max_position: 15
weighttype: 0
fix_ncbi: 1
dir: data
cores: 6
bayesian: false
