name: Documentation

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-docs:

    runs-on: ubuntu-latest

    steps:


    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check out repository
      uses: actions/checkout@master
      with:
        fetch-depth: 0


    # install & configure poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1 # v1.2.0
      with:
        version: 1.2.0a2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    # load cached venv if cache exists
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-docs-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    # install dependencies if cache does not exist
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --with docs

    # - name: install
    #   run: poetry install --with docs

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run make clean && poetry run make html
        cp -r build/html/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: gh-pages
