name: Documentation

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # install & configure poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1 # v1.2.0
      with:
        version: 1.2.0a2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: install
      run: poetry install --only docs

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run make clean && poetry run make html
        cp -r build/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: gh-pages
